apiVersion: v2
name: dashfrog
description: Business Observability on OpenTelemetry - Helm Chart
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - observability
  - opentelemetry
  - metrics
  - monitoring
home: https://github.com/towlabs/dashfrog
sources:
  - https://github.com/towlabs/dashfrog
maintainers:
  - name: DashFrog Team
dependencies:
  - name: postgresql
    version: "15.5.x"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: prometheus
    version: "25.x.x"
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
