{{- if .Values.otelCollector.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dashfrog.otelCollector.fullname" . }}
  labels:
    {{- include "dashfrog.labels" . | nindent 4 }}
    app.kubernetes.io/component: otel-collector
spec:
  type: {{ .Values.otelCollector.service.type }}
  ports:
    - port: {{ .Values.otelCollector.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.otelCollector.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.otelCollector.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "dashfrog.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: otel-collector
{{- end }}
