services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    ports:
      - "8080:8080"
      - "8000:8000"
    networks:
      - dashfrog

  postgres:
    extends:
      file: ../docker-compose.test.yml
      service: postgres
    profiles:
      - services

  otel-collector:
    extends:
      file: ../docker-compose.test.yml
      service: otel-collector
    profiles:
      - services

  prometheus:
    extends:
      file: ../docker-compose.test.yml
      service: prometheus
    profiles:
      - services

networks:
  dashfrog:
    driver: bridge

volumes:
  postgres-data:
  prometheus-data:
